"""Organoid growth charts: fit the final model chosen on day 2.

Final model (decided 2026-10-06 on the Velasco test set, notebooks/03_pcntoolkit_blr.ipynb step 9):
PCNtoolkit BLR on logit(y), cubic B-spline (5 knots) on age for the mean, heteroskedastic,
publication batch effect (per-publication mean offset and per-publication noise level).
Saved in results/ as `blr_hetero_batch_logit`.

Usage from a notebook in notebooks/:

    import sys; sys.path.insert(0, "..")
    from src.growth_chart import fit_growth_chart, plot_growth_chart, test_metrics

    df = ...  # one protocol, with columns sample, age, publication, <y_col>, split ("train"/"test")
    centiles, zscores = fit_growth_chart(df, "frac_NPC_IP", model_name="final_lancaster_npc")
    plot_growth_chart(centiles, zscores, title="Lancaster, frac_NPC_IP", path="../figures/final_lancaster_npc.png")
    test_metrics(zscores)

Output files (format from CLAUDE.md), in results/<model_name>/:
- centiles.csv: age, p5, p25, p50, p75, p95 (fraction scale). The curve is for one publication (`grid_batch`).
- zscores.csv: sample, age, publication, split, y, mu, sigma, z, loglik (+ mu_logit with the logit transform).
  With the logit transform, mu is the median on the fraction scale, sigma is on the logit scale (do not use it
  to recompute z), and loglik is the log-likelihood on the fraction scale (used for MSLL).

Do not edit this file if you are the teammate; tell Boting what is missing (TASKS_day2.md, file ownership).
"""
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from scipy.special import logit, expit

import pcntoolkit
from pcntoolkit import BLR, BsplineBasisFunction, NormData, NormativeModel

pcntoolkit.util.output.Output.set_show_messages(False)

ROOT = Path(__file__).resolve().parents[1]
Z95 = stats.norm.ppf(0.95)  # 1.645
CENTILE_COLS = ["p5", "p25", "p50", "p75", "p95"]

# Fixed colours for the Velasco publications (Okabe-Ito, colour-blind safe); other publications
# get the remaining Okabe-Ito colours in alphabetical order.
PUB_COLORS = {"Bhaduri, 2020": "#0072B2", "Paulsen, 2022": "#E69F00",
              "Uzquiano, 2022": "#009E73", "Velasco, 2019": "#D55E00"}
EXTRA_COLORS = ["#CC79A7", "#56B4E9", "#F0E442", "#000000", "#999999"]


def _template(batch):
    return BLR(
        basis_function_mean=BsplineBasisFunction(degree=3, nknots=5),
        heteroskedastic=True,
        fixed_effect=batch is not None,
        fixed_effect_var=batch is not None,
    )


def _normdata(name, d, resp, batch):
    return NormData.from_dataframe(name=name, dataframe=d, covariates=["age"], response_vars=[resp],
                                   subject_ids="sample", batch_effects=[batch] if batch else None)


def fit_growth_chart(df, y_col, split_col="split", model_name="final", batch="publication", transform="logit",
                     age_grid=None, grid_batch=None, clip=(0.005, 0.995), results_dir=None):
    """Fit the final BLR on df (one protocol), write results/<model_name>/{centiles,zscores}.csv, return (centiles, zscores).

    df          one protocol; needs columns sample, age, publication, y_col, split_col.
    y_col       the fraction to model, e.g. "frac_NPC_IP", "frac_neuron", "frac_glia".
    split_col   column with "train" / "test". Only train rows are used for fitting; all rows get a z-score.
    batch       batch-effect column ("publication"), or None for no batch effect.
    transform   "logit" (final model) or None (plain Gaussian BLR on the fraction).
    age_grid    ages for centiles.csv. Default: from min(20, youngest sample) to the oldest sample, every day.
    grid_batch  which publication's curve to draw. Default: the one with the most train samples.
    clip        y is clipped to this range before the logit. A warning is printed if many samples hit the floor.
    results_dir default <repo>/results. Pass a scratch folder for experiments (e.g. subsampling).
    """
    if transform not in ("logit", None):
        raise ValueError("transform must be 'logit' or None")
    d = df.reset_index(drop=True).copy()
    for col in ["sample", "age", "publication", y_col, split_col]:
        if col not in d:
            raise KeyError(f"df has no column '{col}'")
    d["split"] = d[split_col]
    y = d[y_col].astype(float).values

    if transform == "logit":
        n_floor = int((y < clip[0]).sum())
        if n_floor > 0.1 * len(d):
            print(f"WARNING: {n_floor} of {len(d)} samples have {y_col} < {clip[0]} and are clipped to it. "
                  "The logit model treats them all as the same value; centiles near 0 and their z-scores "
                  "are unreliable. Consider restricting the age range.")
        resp = f"{y_col}_logit"
        d[resp] = logit(np.clip(y, *clip))
    else:
        resp = y_col

    train = d[d["split"] == "train"]
    model = NormativeModel(_template(batch), savemodel=False, saveresults=False, saveplots=False)
    model.fit(_normdata("train", train, resp, batch))

    # Centiles on the age grid, for one publication.
    if age_grid is None:
        age_grid = np.arange(int(min(20, d["age"].min())), int(d["age"].max()) + 1)
    age_grid = np.asarray(age_grid)
    grid = pd.DataFrame({"sample": [f"grid_{a}" for a in age_grid], "age": age_grid, resp: 0.0})
    if batch:
        if grid_batch is None:
            grid_batch = train[batch].value_counts().idxmax()
        grid[batch] = grid_batch
    nd_grid = _normdata("grid", grid, resp, batch)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")  # the dummy y column triggers harmless divide-by-zero warnings
        model.predict(nd_grid)
    c = nd_grid.centiles.values[:, :, 0]
    if transform == "logit":
        c = expit(c)
    centiles = pd.DataFrame(c.T, columns=CENTILE_COLS)
    centiles.insert(0, "age", age_grid)
    centiles.attrs["grid_batch"] = grid_batch

    # z-scores for every sample whose publication was seen in training (others get NaN).
    seen = d[batch].isin(train[batch].unique()).values if batch else np.ones(len(d), bool)
    zs = pd.DataFrame({"sample": d["sample"], "age": d["age"], "publication": d["publication"],
                       "split": d["split"], "y": y})
    for col in ["mu", "sigma", "z", "loglik"] + (["mu_logit"] if transform == "logit" else []):
        zs[col] = np.nan
    if (~seen).any():
        print(f"NOTE: {(~seen).sum()} samples from publications absent in train get no z-score.")
    nd_all = _normdata("all", d[seen], resp, batch)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        model.predict(nd_all)
    ca = nd_all.centiles.values[:, :, 0]
    mu_t, sd_t = ca[2], (ca[4] - ca[2]) / Z95
    zs.loc[seen, "z"] = nd_all.Z.values.ravel()
    if transform == "logit":
        p = np.clip(y[seen], *clip)
        zs.loc[seen, "mu"] = expit(mu_t)
        zs.loc[seen, "mu_logit"] = mu_t
        zs.loc[seen, "loglik"] = stats.norm.logpdf(logit(p), mu_t, sd_t) - np.log(p * (1 - p))
    else:
        zs.loc[seen, "mu"] = mu_t
        zs.loc[seen, "loglik"] = stats.norm.logpdf(y[seen], mu_t, sd_t)
    zs.loc[seen, "sigma"] = sd_t

    out = Path(results_dir) if results_dir else ROOT / "results"
    out = out / model_name
    out.mkdir(parents=True, exist_ok=True)
    centiles.to_csv(out / "centiles.csv", index=False)
    zs.to_csv(out / "zscores.csv", index=False)
    return centiles, zs


def test_metrics(zscores):
    """Test-set EV, SMSE, MSLL and z calibration from a zscores table (same formulas as notebook 03, step 8)."""
    z = zscores.dropna(subset=["z"])
    tr, te = z[z["split"] == "train"], z[z["split"] == "test"]
    y, mu = te["y"], te["mu"]
    ll_model = te["loglik"] if "loglik" in te else stats.norm.logpdf(y, mu, te["sigma"])
    ll_trivial = stats.norm.logpdf(y, tr["y"].mean(), tr["y"].std())
    return pd.Series({
        "n_test": len(te),
        "EV": 1 - np.var(y - mu) / np.var(y),
        "SMSE": np.mean((y - mu) ** 2) / np.var(y),
        "MSLL": np.mean(ll_trivial - ll_model),
        "z_mean": te["z"].mean(),
        "z_sd": te["z"].std(),
        "z_skew": stats.skew(te["z"], bias=False),
        "z_kurtosis": stats.kurtosis(te["z"], bias=False),
        "pct_abs_z_gt_1.96": 100 * np.mean(np.abs(te["z"]) > 1.96),
    })


def plot_growth_chart(centiles, zscores, title=None, path=None, y_label=None, annotate_z=None, ax=None):
    """Centile lines + all samples coloured by publication, test samples ringed.

    annotate_z  e.g. 1.96: ring samples with |z| above it in red and write their z next to them.
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(10, 4.8))
    ax.fill_between(centiles["age"], centiles["p5"], centiles["p95"], color="0.85", alpha=0.5, lw=0)
    for col, ls, lw in [("p5", ":", 1.2), ("p25", "--", 1.2), ("p50", "-", 2), ("p75", "--", 1.2), ("p95", ":", 1.2)]:
        ax.plot(centiles["age"], centiles[col], color="0.25", ls=ls, lw=lw)
    # Centile labels at the right end, pushed apart so they never overlap.
    y_range = max(zscores["y"].max(), centiles["p95"].max()) - min(0, centiles["p5"].min())
    gap = 0.045 * y_range
    label_y = list(centiles[CENTILE_COLS].iloc[-1].values)
    for i in range(1, 5):
        label_y[i] = max(label_y[i], label_y[i - 1] + gap)
    for col, ly in zip(CENTILE_COLS, label_y):
        ax.text(centiles["age"].iloc[-1] + 2, ly, col, va="center", fontsize=8, color="0.25")

    pubs = sorted(zscores["publication"].unique())
    extra = iter(EXTRA_COLORS + list(PUB_COLORS.values()))
    colors = {p: PUB_COLORS[p] if p in PUB_COLORS else next(extra) for p in pubs}
    for pub in pubs:
        g = zscores[zscores["publication"] == pub]
        ax.scatter(g["age"], g["y"], s=22, color=colors[pub], alpha=0.85, label=pub, zorder=3)
    t = zscores[zscores["split"] == "test"]
    ax.scatter(t["age"], t["y"], s=70, facecolors="none", edgecolors="k", lw=1, label="test (held out)", zorder=4)

    if annotate_z is not None:
        out = zscores[zscores["z"].abs() > annotate_z]
        ax.scatter(out["age"], out["y"], s=130, facecolors="none", edgecolors="#B00020", lw=1.5,
                   label=f"|z| > {annotate_z}", zorder=5)
        # One label per cluster of flagged samples (same age within 3 days, y within 8% of the range).
        out = out.sort_values(["age", "y"])
        clusters = []
        for _, r in out.iterrows():
            if clusters and abs(r["age"] - clusters[-1][-1]["age"]) <= 3 and abs(r["y"] - clusters[-1][-1]["y"]) <= 0.08 * y_range:
                clusters[-1].append(r)
            else:
                clusters.append([r])
        for cl in clusters:
            zs_txt = ", ".join(f"{r['z']:+.1f}" for r in cl)
            ax.annotate(f"z = {zs_txt}", (cl[-1]["age"], max(r["y"] for r in cl)), xytext=(8, 6),
                        textcoords="offset points", fontsize=8, color="#B00020")

    ax.axhline(0, color="0.6", lw=0.8)
    ax.set_xlabel("age (days in culture)")
    ax.set_ylabel(y_label or "fraction of cells")
    ax.set_xlim(centiles["age"].min() - 5, centiles["age"].max() + 13)
    if title:
        gb = centiles.attrs.get("grid_batch")
        ax.set_title(title + (f"\ncentile lines for {gb}" if gb else ""), fontsize=11)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8, loc="upper left", bbox_to_anchor=(1.07, 1), frameon=False)   # outside: never covers data
    if path is not None:
        plt.tight_layout()
        plt.savefig(path, dpi=150, bbox_inches="tight")
    return ax
